### ISSUE TITLE
trouble running the django-webapp example

### ISSUE THREAD

**Issue by Jacobus-afk** [pyproject-nix/uv2nix#71]
Hi

Chances are good that I'm doing something wrong, as nix has a tendency to break my brain 😕 

I'm trying to get the django-webapp example to run, but i'm running into errors when building or creating a shell

Steps to reproduce

`nix flake init --template github:pyproject-nix/uv2nix#django-webapp`

then `nix develop .` results in the following error:

```
error: builder for '/nix/store/ppq81pljmf4q0zri3km570ql3z8zif2h-hatchling-1.26.3.drv' failed with exit code 2;
       last 25 log lines:
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > Executing pyprojectConfigurePhase
       > Finished executing pyprojectConfigurePhase
       > Running phase: buildPhase
       > Executing pyprojectBuildPhase
       > Creating a wheel...
       > warning: Ignoring invalid `SSL_CERT_FILE`. File does not exist: /no-cert-file.crt.
       > Building wheel...
       > Traceback (most recent call last):
       >   File "<string>", line 11, in <module>
       >   File "/build/hatchling-1.26.3/src/hatchling/build.py", line 58, in build_wheel
       >     return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
       >                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/build/hatchling-1.26.3/src/hatchling/builders/plugin/interface.py", line 90, in build
       >     self.metadata.validate_fields()
       >   File "/build/hatchling-1.26.3/src/hatchling/metadata/core.py", line 266, in validate_fields
       >     self.core.validate_fields()
       >   File "/build/hatchling-1.26.3/src/hatchling/metadata/core.py", line 1366, in validate_fields
       >     getattr(self, attribute)
       >   File "/build/hatchling-1.26.3/src/hatchling/metadata/core.py", line 677, in license
       >     from packaging.licenses import canonicalize_license_expression
       > ModuleNotFoundError: No module named 'packaging.licenses'
       > error: Build backend failed to build wheel through `build_wheel` (exit status: 1)
       For full logs, run 'nix log /nix/store/ppq81pljmf4q0zri3km570ql3z8zif2h-hatchling-1.26.3.drv'.
error: 1 dependencies of derivation '/nix/store/cgia0gqcphc3p3kxn9vi703j6yam72il-django-webapp-dev-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mdndflxpdmd9yzfa2lxd32nm9fmrzvpi-nix-shell-env.drv' failed to build
```

---

running `nix build .#docker` also results in a similar error:

```
error: builder for '/nix/store/ppq81pljmf4q0zri3km570ql3z8zif2h-hatchling-1.26.3.drv' failed with exit code 2;
       last 25 log lines:
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > Executing pyprojectConfigurePhase
       > Finished executing pyprojectConfigurePhase
       > Running phase: buildPhase
       > Executing pyprojectBuildPhase
       > Creating a wheel...
       > warning: Ignoring invalid `SSL_CERT_FILE`. File does not exist: /no-cert-file.crt.
       > Building wheel...
       > Traceback (most recent call last):
       >   File "<string>", line 11, in <module>
       >   File "/build/hatchling-1.26.3/src/hatchling/build.py", line 58, in build_wheel
       >     return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
       >                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/build/hatchling-1.26.3/src/hatchling/builders/plugin/interface.py", line 90, in build
       >     self.metadata.validate_fields()
       >   File "/build/hatchling-1.26.3/src/hatchling/metadata/core.py", line 266, in validate_fields
       >     self.core.validate_fields()
       >   File "/build/hatchling-1.26.3/src/hatchling/metadata/core.py", line 1366, in validate_fields
       >     getattr(self, attribute)
       >   File "/build/hatchling-1.26.3/src/hatchling/metadata/core.py", line 677, in license
       >     from packaging.licenses import canonicalize_license_expression
       > ModuleNotFoundError: No module named 'packaging.licenses'
       > error: Build backend failed to build wheel through `build_wheel` (exit status: 1)
       For full logs, run 'nix log /nix/store/ppq81pljmf4q0zri3km570ql3z8zif2h-hatchling-1.26.3.drv'.
error: 1 dependencies of derivation '/nix/store/rz8kixkpcx6dcq5pxxhr8lr96f8wv2af-django-webapp-0.1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pp4zn1z7018y86kvzhh698ypxfq4cbz4-django-webapp-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/a4ldlypzg6avswrdg2pc846jzd7rbmf0-django-webapp-base.json.drv' failed to build
error: 1 dependencies of derivation '/nix/store/m7ksag5ca2y5awfdgqb1gi7555ylmfch-django-webapp-conf.json.drv' failed to build
error: 1 dependencies of derivation '/nix/store/iaxhqqf54ibb2hp7595z1x8rv60pi252-stream-django-webapp.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mnpf58mfbdxky8fcgsqgpin50dwri71a-django-webapp.tar.gz.drv' failed to build
```

**Comment by adisbladis** [comment]
`packaging.licenses` is a relatively new thing, and the version contained in `uv.lock` for the django example was too old to work with the current `hatchling` version.
All that's needed was a [version bump](214a494354a35deb3200c1e3a00df0a1c09cf878).

One observation:

- Maybe flake templates should be shipped _without_ a `uv.lock`
  I added a lock file to make the examples work OOTB. 
  Because flake templates lack a mechanism to update embedded locks post checkout it might be a better idea to have a little bit of initial friction in setting things up to avoid stale dependencies.
